[build]
  publish = "frontend"
  command = "npm install && cp -r \"./layers expression\" ./frontend/"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/emotion"
  to = "/.netlify/functions/emotion"
  status = 200
  force = true

[[redirects]]
  from = "/api/stream"
  to = "/.netlify/functions/stream"
  status = 200
  force = true
